 
language: cpp
os:
  - linux
  - osx
sudo: require
dist: xenial
compiler:
  - gcc
osx_image: xcode10.2
before_install:
  - export STAGE=before_install
  - ./scripts/travis.sh
script:
  - export STAGE=script
  - ./scripts/travis.sh
  
after_success:
  - export STAGE=after_success
  - ./scripts/travis.sh
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
  
  
addons:
  homebrew:
    taps:
      - kde-mac/kde
    packages:
      - qt5
      - gstreamer
      - gst-plugins-good
      - gst-plugins-bad
      - gst-plugins-ugly
      - cmake
      - libmusicbrainz
      - taglib
      - kf5-extra-cmake-modules
    update: true

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
