version: 1.0.{build}
image: Visual Studio 2019
before_build:
- cmd: dotnet restore
build:
  verbosity: normal
before_deploy:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/deploy.ps1'))
