branches:
  only:
    - master

install:
  - set QTDIR=set QTDIR=C:\Qt\5.12\msvc2017_64
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - qmake AleePlayer.pro
  - mingw32-make
after_build:
  - windeployqt release/fastqt.exe
  - cmd: cp LICENSE release/LICENSE.txt"
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\AleePlayer-*.exe
  - path: release
    type: zip
